import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

import '../services/settings_service.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key, required this.settings});

  final SettingsService settings;

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  final _apiKeyController = TextEditingController();
  final _outputDirController = TextEditingController();
  String _model = SettingsService.defaultModel;
  bool _includeAi = false;
  bool _loading = true;
  bool _obscure = true;
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final key = await widget.settings.getApiKey();
    final model = await widget.settings.getModel();
    final include = await widget.settings.getIncludeAi();
    final outputDir = await widget.settings.getOutputDir();
    if (!mounted) return;
    setState(() {
      _apiKeyController.text = key ?? '';
      _outputDirController.text = outputDir ?? '';
      _model = model;
      _includeAi = include;
      _loading = false;
    });
  }

  Future<void> _save() async {
    setState(() => _saving = true);
    await widget.settings.setApiKey(_apiKeyController.text.trim());
    await widget.settings.setModel(_model);
    await widget.settings.setIncludeAi(_includeAi);
    await widget.settings.setOutputDir(_outputDirController.text.trim());
    if (!mounted) return;
    setState(() => _saving = false);
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Settings saved.')),
      );
    }
  }

  Future<void> _browseOutputDir() async {
    final picked = await FilePicker.platform.getDirectoryPath(
      dialogTitle: 'Choose folder for saved reports',
      initialDirectory:
          _outputDirController.text.isEmpty ? null : _outputDirController.text,
    );
    if (picked == null) return;
    setState(() => _outputDirController.text = picked);
  }

  @override
  void dispose() {
    _apiKeyController.dispose();
    _outputDirController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }
    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Anthropic API', style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 8),
            const Text(
              'Required for AI Insights. The key is stored encrypted on this machine via flutter_secure_storage. '
              'Leave empty to disable AI insights.',
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _apiKeyController,
              obscureText: _obscure,
              decoration: InputDecoration(
                labelText: 'API key',
                hintText: 'sk-ant-…',
                border: const OutlineInputBorder(),
                suffixIcon: IconButton(
                  icon: Icon(_obscure ? Icons.visibility : Icons.visibility_off),
                  onPressed: () => setState(() => _obscure = !_obscure),
                ),
              ),
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
              initialValue: _model,
              decoration: const InputDecoration(
                labelText: 'Model',
                border: OutlineInputBorder(),
              ),
              items: SettingsService.supportedModels
                  .map((m) => DropdownMenuItem(value: m, child: Text(m)))
                  .toList(),
              onChanged: (v) => setState(() => _model = v ?? _model),
            ),
            const SizedBox(height: 16),
            SwitchListTile(
              contentPadding: EdgeInsets.zero,
              title: const Text('Include AI Insights in the report'),
              subtitle: const Text(
                'Adds an "AI Insights" section generated by the configured Anthropic model. '
                'Sends only an aggregated digest, never raw log lines.',
              ),
              value: _includeAi,
              onChanged: (v) => setState(() => _includeAi = v),
            ),
            const SizedBox(height: 24),
            Text('Saved reports', style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 8),
            const Text(
              'Folder where the "Save to disk" action writes report-*.md files. '
              'Leave empty to use the default <Documents>/log-analysis.',
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _outputDirController,
              readOnly: true,
              decoration: InputDecoration(
                labelText: 'Output folder',
                hintText: '<Documents>/log-analysis',
                border: const OutlineInputBorder(),
                suffixIcon: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (_outputDirController.text.isNotEmpty)
                      IconButton(
                        tooltip: 'Reset to default',
                        icon: const Icon(Icons.clear),
                        onPressed: () => setState(() => _outputDirController.clear()),
                      ),
                    IconButton(
                      tooltip: 'Browse…',
                      icon: const Icon(Icons.folder_open),
                      onPressed: _browseOutputDir,
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 24),
            Row(
              children: [
                FilledButton.icon(
                  onPressed: _saving ? null : _save,
                  icon: const Icon(Icons.save),
                  label: const Text('Save'),
                ),
                const SizedBox(width: 12),
                OutlinedButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text('Close'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
